server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderService # order 服务端名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
#      discovery:
#        cluster-name: HZ
#        namespace: 2e7fc661-032d-49cc-b6d5-52b78e46b1b9 # 命名空间做服务隔离，此为 dev 的命名空间的id
#        ephemeral: false #将服务改成非临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url: #eureka 服务地址
#      defaultZone: http://127.0.0.1:10086/eureka/

userService:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则，只针对 userService 这一个服务
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients:
      - userService # 指定对 userService这个服务进行饥饿加载
feign:
  client:
    config:
      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
        loggerLevel: FULL #  日志级别 包含四种不同的级别：NONE、BASIC、HEADERS、FULL
  httpclient: #配置连接池
    enabled: true #开启 feign 对 HttpClient 的支持
    max-connections: 200  # 最大连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
