server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: user-service #路由id ,自定义，保证唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址，http就是固定地址
          uri: lb://userService # 路由的目标地址， lb 是负载均衡，后面是服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件, spring提供了11种断言方式，根据官方文档按业务场景设置
            - Path=/user/** # 这个是按路径匹配，只要是以/user/ 开头的请求就都匹配
            # - After=2037-01-20T17:42:47.789-07:00[America/Denver]
#          filters: # 针对单个服务过滤器
#            - AddRequestHeader=truth, xiexinyu is awesome!
        - id: order-service
          uri: lb://orderService
          predicates:
            - Path=/order/**
      default-filters: # 针对所有服务的过滤器
        - AddRequestHeader=truth, xiexinyu is awesome!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期